name: Run NPM script
on:
  repository_dispatch:
    types: [run-prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
      - run: npm i
      - run: npm run build
