name: Run NPM script
on:
  repository_dispatch:
    types: [run-prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm i

      - name: Run webflow devlink sync
        run: npx webflow devlink sync

      - name: Build project
        run: npm run build && npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
