name: Run NPM script
on:
  repository_dispatch:
    types: [run-prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: git@github.com:val10010/bereginia.git
          ref: gh-pages
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
      - run: npm i
      - name: Deploy
        run: npx webflow devlink sync && npm run build && npx gh-pages -d build -u "val10010 <valantine10010@gmail.com>"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
