name: Run NPM script
on:
  repository_dispatch:
    types: [run-prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm i

      - name: Run webflow devlink sync
        run: npx webflow devlink sync

      - name: Build project
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Commit build to gh-pages branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b gh-pages
          git add -f build
          git commit -m "Deploying to gh-pages"
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
