name: Run NPM script
on:
  repository_dispatch:
    types: [run-prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
      - run: npm i
      - name: Setup Git
        run: |
          git config --global user.email "valantine10010@gmail.com"
          git config --global user.name "val10010"
      - name: Deploy
        run: npx webflow devlink sync && npm run build && npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
